# Generated by Django 4.0.4 on 2022-05-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusro',
            new_name='Curso',
        ),
    ]
